version: '2'
services:
  base:
    image: node:11
    volumes:
      - nodemodules:/usr/src/node_modules
      - .:/usr/src
    working_dir: /usr/src
  install:
    extends:
      service: base
    command: npm install
  build:
    extends:
      service: base
    command: npm run build
  lint:
    extends:
      service: base
    command: npm run lint
  compile:
    extends:
      service: base
    command: npm run tsc
  develop:
    extends:
      service: base
    command: npm run develop
    ports:
      - 1234:1234
volumes:
  nodemodules:
    external: true
