version: '3'
services:
  start:
    image: cavez_prod:latest
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    command: 'npm run start'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    ports:
      - '1234:1234/tcp'
      - '19900:20000/udp'