version: '3.4'
services:
  start:
    image: cavez_prod:latest
    network_mode: host
    command: 'npm run start'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
